[project]
name = "infosecunplugged-website"
requires-python = ">=3.10"
version = "1.0.0"

[tool.poetry.dependencies]
jinja2 = "3.1.6"
markdown = "3.9"
python-slugify = "8.0.4"
pyyaml = "6.0.2"

[tool.poetry.group.dev.dependencies]
tomlkit = "^0.13.3"

